### ISSUE TITLE
Catkin_make fails ! Could you please help me find out the cause of this error?

### ISSUE THREAD

**Issue by Srichitra-S** [issaiass/jetbot_od#1]
jetbot_od/src/nodelet/yolo_nodelet.cpp:56:10: fatal error: opencv2/dnn/dnn.hpp: No such file or directory
 #include <opencv2/dnn/dnn.hpp>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
jetbot_od/CMakeFiles/jetbot_od.dir/build.make:110: recipe for target 'jetbot_od/CMakeFiles/jetbot_od.dir/src/nodelet/yolo_nodelet.cpp.o' failed
make[2]: *** [jetbot_od/CMakeFiles/jetbot_od.dir/src/nodelet/yolo_nodelet.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....

**Comment by issaiass** [comment]
It is because probably you do not have opencv installed and the version must be above 3.4.

In my local machine is at /usr/include/opencv4/opencv2

**Comment by Srichitra-S** [comment]
I installed openCV version 4 , but still getting the same error.

**Comment by issaiass** [comment]
Did you have those packages installed?

![image](https://user-images.githubusercontent.com/4116031/101927851-ec4ad500-3ba2-11eb-819d-a8584b46e5c1.png)
![image](https://user-images.githubusercontent.com/4116031/101927894-f967c400-3ba2-11eb-8724-bed95bce7a81.png)
![image](https://user-images.githubusercontent.com/4116031/101927966-0edcee00-3ba3-11eb-9f71-3371b8645829.png)
![image](https://user-images.githubusercontent.com/4116031/101928004-1603fc00-3ba3-11eb-9fff-9cfe03577105.png)

**Comment by Srichitra-S** [comment]
![opencv](https://user-images.githubusercontent.com/62196293/101927923-057f7000-3bfb-11eb-9417-dfaed3538826.png)

version is 4 but there is no directory /usr/include/opencv4/opencv2

**Comment by issaiass** [comment]
> ![opencv](https://user-images.githubusercontent.com/62196293/101927923-057f7000-3bfb-11eb-9417-dfaed3538826.png)
> 
> version is 4 but there is no directory /usr/include/opencv4/opencv2

But this is python, not C++

**Comment by issaiass** [comment]
You could build the python version with 4.0 and then without the C++ version, you must check if you have the C++ installation working

**Comment by Srichitra-S** [comment]
> You could build the python version with 4.0 and then without the C++ version, you must check if you have the C++ installation working

How do I check that?

**Comment by issaiass** [comment]
> > You could build the python version with 4.0 and then without the C++ version, you must check if you have the C++ installation working
> 
> How do I check that?

https://www.learnopencv.com/how-to-find-opencv-version-python-cpp/

**Comment by issaiass** [comment]
You can also check the build information by:

$ python
>> import cv2
>> print(cv2.getBuildInformation())
